config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "fijas#inicio"


  get 'gestion_archivos/subir'
  post 'gestion_archivos/subir'
  get 'gestion_archivos/listar', as: "listar"
  post 'gestion_archivos/borrar'
  get 'gestion_archivos/guardar_comentario'
  post 'gestion_archivos/guardar_comentario'

  ## Chat
  get 'mensajes/index'
  get 'mensajes/create'

  ## Fijas
  get '/acceder', to: 'sesiones#new'
  post '/acceder', to: 'sesiones#create'
  delete '/salir', to: "sesiones#destroy"

  get '/acerca', to: 'fijas#acerca'
    #get '/ayuda', to: 'fijas#ayuda' # Anulado para nombrar la ruta
  get '/ayuda', to: 'fijas#ayuda', as: "sos"
  get '/contacto', to: 'fijas#contacto'

  get '/registro', to: 'usuarios#new'
  post "/registro", to: "usuarios#create"

  get "/microentradas", to: 'microentradas#create', microentrada: { contenido: "" }

  resources :usuarios do
      # member permite que la URL de cada usuario ejecute el bloque
      # collection opera sin :id
    member do
        # usuarios/1/siguiendo y ...
      get :siguiendo, :seguidores
    end
  end

  resources :activacion_cuentas, only: [:edit]
  resources :reseteo_passwords, only: [:new, :create, :edit, :update]
  resources :microentradas, only: [:create, :destroy]
  resources :relaciones, only: [:create, :destroy]

    # Para el chat del Cable
  # get '/chat', to: 'mensajes#index'
  resources :mensajes

  mount ActionCable.server, at: '/cable'
end

app/views/compartido/_estadisticas.html.erb
<% @usuario ||= usuario_actual %>
<div class="estadisticas">
	<a href="<%= siguiendo_usuario_path(@usuario) %>">
		<strong id="siguiendo" class="estadistica">
			<%= @usuario.siguiendo.count %>
		</strong>
		siguiendo
	</a>
	<a href="<%= seguidores_usuario_path(@usuario) %>">
		<strong id="seguidores" class="estadistica">
			<%= @usuario.seguidores.count %>
		</strong>
		seguidores
	</a>
</div>

app/views/compartido/_formulario_microentrada.html.erb
<%= form_for(@microentrada) do |f| %>
	<%= render "compartido/mensaje_error", objeto: f.object %>
	<div class="field">
		<%= f.text_area :contenido, placeholder: "Crea una nueva microentrada..." %>
	</div>
	<%= f.submit "Publicar", class: "btn btn-primary" %>
	<span class="imagen">
			<!-- accept: basado en la Whitelist del modelo Microentrada -->
		<%= f.file_field :imagen, accept: "image/jpeg, image/gif, image/png" %>
	</span>
<% end %>

<script type="text/javascript">
	$('#imagen_microentrada').bind('change', function(){
		var peso_en_mb = this.files[0].size/1024/1024;
		if (peso_en_mb > 5){
			alert('El tamaño máximo de la imagen es de 5MB. Por favor, escoge otra.');
		}
	})
</script>

app/views/compartido/_info_usuario.html.erb
<%= link_to gravatarPara(usuario_actual, medida: 50), usuario_actual %>
<h1><%= usuario_actual.nombre %></h1>
<span><%= link_to "Ver mi perfil", usuario_actual %></span>
<span><%= pluralize(usuario_actual.microentradas.count, "microentradas") %></span>

app/views/compartido/_mensaje_error.html.erb
<% if objeto.errors.any? %>
	<div id="explicacion_error">
		<div class="alert alert-danger">
			El formulario contiene <%= pluralize(objeto.errors.count, 'error') %>
		</div>
		<ul>
			<% objeto.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/compartido/_publicado.html.erb
<% if @objetos_publicados.any? %>
	<ol class="microentradas">
		<%= render @objetos_publicados %>
	</ol>
	<%= will_paginate @objetos_publicados %>
<% end %>