config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "fijas#inicio"


  get 'gestion_archivos/subir'
  post 'gestion_archivos/subir'
  get 'gestion_archivos/listar', as: "listar"
  post 'gestion_archivos/borrar'
  get 'gestion_archivos/guardar_comentario'
  post 'gestion_archivos/guardar_comentario'

  ## Chat
  get 'mensajes/index'
  get 'mensajes/create'

  ## Fijas
  get '/acceder', to: 'sesiones#new'
  post '/acceder', to: 'sesiones#create'
  delete '/salir', to: "sesiones#destroy"

  get '/acerca', to: 'fijas#acerca'
    #get '/ayuda', to: 'fijas#ayuda' # Anulado para nombrar la ruta
  get '/ayuda', to: 'fijas#ayuda', as: "sos"
  get '/contacto', to: 'fijas#contacto'

  get '/registro', to: 'usuarios#new'
  post "/registro", to: "usuarios#create"

  get "/microentradas", to: 'microentradas#create', microentrada: { contenido: "" }

  resources :usuarios do
      # member permite que la URL de cada usuario ejecute el bloque
      # collection opera sin :id
    member do
        # usuarios/1/siguiendo y ...
      get :siguiendo, :seguidores
    end
  end

  resources :activacion_cuentas, only: [:edit]
  resources :reseteo_passwords, only: [:new, :create, :edit, :update]
  resources :microentradas, only: [:create, :destroy]
  resources :relaciones, only: [:create, :destroy]

    # Para el chat del Cable
  # get '/chat', to: 'mensajes#index'
  resources :mensajes

  mount ActionCable.server, at: '/cable'
end

app/controllers/reseteo_passwords_controller.rb
class ReseteoPasswordsController < ApplicationController
	before_action :obtener_usuario, only: [:edit, :update]
	before_action :usuario_valido, only: [:edit, :update]
	before_action :comprobar_expiracion, only: [:edit, :update]

  def new
  end

  def create
  	@usuario = Usuario.find_by(email: params[:reseteo_password][:email].downcase)
  	if @usuario
  		@usuario.crear_digest_reseteo
  		@usuario.enviar_mail_reseteo
  		flash[:info] = "Enviado email con las intrucciones para restablecer la contraseña."
  		redirect_to root_url
  	else
  		flash.now[:danger] = "La dirección email no está registrada."
  		render "new"
  	end
  end

  def edit
  end

  def update
  	if params[:usuario][:password].empty?
  		@usuario.errors.add(:password, "no puede estar en blanco.")
  		render "edit"
  	elsif @usuario.update_attributes(parametros_usuario)
  		dar_acceso_a @usuario
  			# Medida de seguridad, en caso de pulsar 'Atras' en el navegador
  		@usuario.update_attribute(:digest_reseteo, nil)
  		flash[:success] = "La contraseña ha sido actualizada."
  		redirect_to @usuario
  	else
  		render "edit"
  	end
  end

  private
  	def parametros_usuario
  		params.require(:usuario).permit(:password, :password_confirmation)
  	end

  	def obtener_usuario
  		@usuario = Usuario.find_by(email: params[:email])
  	end

  	def usuario_valido
  		unless(@usuario && @usuario.activado? && @usuario.autentificado?(:reseteo, params[:id]))
  			redirect_to root_url
  		end
  	end

  	def comprobar_expiracion
  		if @usuario.reseteo_password_expirado?
  			flash[:danger] = "El restablecimento de la contraseña ha expirado"
  			redirect_to new_reseteo_password_url
  		end
  	end
end

app/helpers/reseteo_passwords_helper.rb
module ReseteoPasswordsHelper
end

app/views/reseteo_passwords/edit.html.erb
<% provide(:titulo, "Restablecer contraseña") %>

<h1>Restablecer contraseña en Primera App</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@usuario, url: reseteo_password_path(params[:id])) do |f| %>
			<%= render 'compartido/mensaje_error', objeto: f.object %>

			<%= hidden_field_tag :email, @usuario.email %>

			<%= f.label :password %>
			<%= f.password_field :password, class: 'form-control' %>

			<%= f.label :password_confirmation, "Confirma la contraseña" %>
			<%= f.password_field :password_confirmation, class: 'form-control' %>

			<%= f.submit "Actualizar contraseña", class: 'btn btn-primary' %>
		<% end %>

	</div>
</div>

app/views/reseteo_passwords/new.html.erb
<% provide(:titulo, "Restablecer contraseña") %>
<h1>Restablecer contraseña</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(:reseteo_password, url: reseteo_passwords_path) do |f| %>

			<%= f.label :email %>
			<%= f.email_field :email, class: 'form-control' %>

			<%= f.submit "Enviar", class: 'btn btn-primary' %>

		<% end %>
	</div>
</div>