config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "fijas#inicio"


  get 'gestion_archivos/subir'
  post 'gestion_archivos/subir'
  get 'gestion_archivos/listar', as: "listar"
  post 'gestion_archivos/borrar'
  get 'gestion_archivos/guardar_comentario'
  post 'gestion_archivos/guardar_comentario'

  ## Chat
  get 'mensajes/index'
  get 'mensajes/create'

  ## Fijas
  get '/acceder', to: 'sesiones#new'
  post '/acceder', to: 'sesiones#create'
  delete '/salir', to: "sesiones#destroy"

  get '/acerca', to: 'fijas#acerca'
    #get '/ayuda', to: 'fijas#ayuda' # Anulado para nombrar la ruta
  get '/ayuda', to: 'fijas#ayuda', as: "sos"
  get '/contacto', to: 'fijas#contacto'

  get '/registro', to: 'usuarios#new'
  post "/registro", to: "usuarios#create"

  get "/microentradas", to: 'microentradas#create', microentrada: { contenido: "" }

  resources :usuarios do
      # member permite que la URL de cada usuario ejecute el bloque
      # collection opera sin :id
    member do
        # usuarios/1/siguiendo y ...
      get :siguiendo, :seguidores
    end
  end

  resources :activacion_cuentas, only: [:edit]
  resources :reseteo_passwords, only: [:new, :create, :edit, :update]
  resources :microentradas, only: [:create, :destroy]
  resources :relaciones, only: [:create, :destroy]

    # Para el chat del Cable
  # get '/chat', to: 'mensajes#index'
  resources :mensajes

  mount ActionCable.server, at: '/cable'
end

app/controllers/gestion_archivos_controller.rb
class GestionArchivosController < ApplicationController

	RutaArchivos = 'public/archivos/'
	RutaComentarios = 'public/comentarios/comentarios.txt'

  def subir
  	@formato_erroneo = false
  	if request.post?
  			# Archivo subido por el usuario
  		archivo = params[:archivo_subida]
  			# Nombre original del archivo
  		nombre = archivo.original_filename
  			# Directorio de la subida
  		directorio = RutaArchivos
  			# Obtener la extensión del archivo
  		extension = nombre.slice(nombre.rindex("."), nombre.length).downcase
  			# Comprueba la extensión correcta
  		if extension == ".pdf" or extension == ".doc" or extension == ".docx" or extension == ".png"
  			ruta = File.join(directorio, nombre)
  				# Creación del archivo
  			resultado = File.open(ruta, "wb") { |f| f.write(archivo.read) }
  				# Verifica la subida
  			if resultado
  				subir = "Ok"
  			else
  				subir = "Fracaso"
  			end
  				# Redirige con la variable GET subir
  			redirect_to(controller: "gestion_archivos", action: "listar", subir: subir)
  		else
  			@formato_erroneo = true
  		end
  	end
  end

  def listar
  		# obtenemos la lista del directorio
    @archivos = []
  	archivos = Dir.entries(RutaArchivos)
    archivos.each do |a|
      (a == '.' || a == '..') ? next : @archivos << a
    end
  		# Mensaje que muestra si la pagina viene de otra opcion
  	@mensaje = ""
  		# Comprueba la variable GET subir
  	if params[:subir].present?
  		if params[:subir] == "Ok"
  			@mensaje = "El archivo se ha subido con exito"
  		else
  			@mensaje = "Ha habido un problema con la subida"
  		end
  	end
  		# Comprueba la variable GEt eliminar
  	if params[:eliminar].present?
  		if params[:eliminar] == "Ok"
  			@mensaje = "El archivo se ha eliminado con éxito"
  		else
  			@mensaje = "El archivo no se ha podido elliminar"
  		end
  	end

  	if File.exist?(RutaComentarios)
  		@comentarios = File.read(RutaComentarios)
  	else
  		@comentarios = "Sin comentarios"
  	end
  end

  def borrar
  		# Recuperamos el nombre del archivo
  	archivo = params[:archivo_a_borrar]
  	ruta_al_archivo = RutaArchivos + archivo
  		# Verificamos que el archivo existe
  	if File.exist?(ruta_al_archivo)
  			# Se intenta borrar
  		resultado = File.delete(ruta_al_archivo)
  	else
  			# El archivo no existe
  		resultado = false
  	end
  		# Verificacion del borrado
  	if resultado
  		eliminado = "Ok"
  	else
  		eliminado = "Error"
  	end
  	redirect_to controller: "gestion_archivos", action: "listar", eliminar: eliminado

  end

  def guardar_comentario
  		# Guarda los comentario de POST
  	if request.post?
  			# Guarda en una variablw
  		comentarios = params[:comentarios]
  			# Abre al archivo de comentarios. Si no existe, se crea
  		File.open(RutaComentarios, "wb"){ |f|
  			f.write(comentarios)
  				# Se cierra el archivo para libera memoria
  			f.close()	
  		}
  	end
  		# Verifica si existe el archivo de comentarios
  	if File.exist?(RutaComentarios)
  			# Guarda el contenido del archivo
  		@comentarios = File.read(RutaComentarios)
  	else
  			# No existe el archivo. Se guardan las comillas
  		@comentario = ""
  	end

  end
end

app/helpers/gestion_archivos_helper.rb
module GestionArchivosHelper
end

app/views/gestion_archivos/borrar.html.erb
<h1>GestionArchivos#borrar</h1>
<p>Find me in app/views/gestion_archivos/borrar.html.erb</p>

app/views/gestion_archivos/guardar_comentario.html.erb
<h1><%= controller.action_name %></h1>
<%= form_tag({controller: "gestion_archivos", action: "guardar_comentario"}, method: "post") do %>
	<%= text_area_tag "comentarios", @comentarios, cols: 10, required: "required" %>
	<br>
	<%= submit_tag "Guardar comentario" %>
<% end %>
<p><%= link_to "Volver a la lista de archivos", controller: "gestion_archivos", action: "listar" %></p>

app/views/gestion_archivos/listar.html.erb
<h2>Listado de archivos</h2>
	<!-- Mensaje enviado de la anterior página-->
<% if @mensaje %>
	<div>
	   <strong> <%= @mensaje %> </strong>
	</div>
<% end %>
<% if !flash.empty? %>
  <% flash.each do |tipo_flash, mensaje_flash| %>
    <%= content_tag(:div, mensaje_flash, class: "alert alert-#{tipo_flash}") %>
  <% end %>
<% end %>
	<!-- Enlace a la página de subir archivos -->
<p> <%# link_to "Subir archivo", :controller => "gestion_archivos", :action => "subir" %> </p>
<p> <%= enlace_a "Subir archivo", gestion_archivos_subir_path %> </p>
	<!-- Lista de archivos subidos -->
<ul>
   <% @archivos.each do |a| %>
   <%# if a == "." or a == ".." then next end; %>
   <li class="archivo">
      <strong> <%= a %> </strong> | 
      <a target="_blank" href="/archivos/<%= a %>"> Ver archivo </a> | 
      <%= link_to "Borrar archivo", {:controller => "gestion_archivos", :action => "borrar", :archivo_a_borrar => a}, {:method => "post", :confirm => "Seguro?"} %>
      <%# link_to "Borrar archivo", {:controller => "gestion_archivos", :action => "borrar", :archivo_a_borrar => a}, {:method => "post", :confirm => "Seguro?"} %>
   </li>
   <% end %>
</ul>
<!-- Acá se guarda el nombre del archivo antes de que el formularo sea enviado-->
<hr />
<!-- Comentarios guardados por el usuario. -->
<h2> Últimos Comentarios: </h2>
<div>
   <pre><%= @comentarios; %></pre>
   <%= link_to "Agregar comentarios", :controller => "gestion_archivos", :action => "guardar_comentario" %>
</div>
<div>
	<p>Gracias a la <%= enlace_a "Web de Fernando Gaitan", "https://fernando-gaitan.com.ar/ruby-on-rails-parte-9-subir-y-trabajar-con-archivos/" %></p>
</div>

app/views/gestion_archivos/subir.html.erb
<h2><%= controller.action_name %></h1>
<%= form_tag({controller: "gestion_archivos", action: "subir"}, method: "post", multipart: true) do %>
	<%= file_field_tag "archivo_subida", required: "required" %>
	<%= submit_tag "Subir archivos" %>
<% end %>
<% if @formato_erroneo %>
	<div>
		<p>El formato del archivo es incorrecto. Solo se admiten archivos .pdf, .doc y .docx</p>
	</div>
<% end %>
<p><%= link_to "Volver a la lista de archivos", controler: "gestion_archivos", action: "listar" %></p>